"""add meeting agent tables

Revision ID: 9ca81cc70198
Revises: 20261003
Create Date: 2026-10-03 18:25:40.164529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9ca81cc70198'
down_revision: Union[str, None] = '20261003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blackboard_events',
    sa.Column('owner_id', sa.BigInteger(), nullable=False, comment='事件归属 user_id（防越权）'),
    sa.Column('session_id', sa.String(length=64), nullable=False, comment='关联的 session_id'),
    sa.Column('agent_role', sa.String(length=32), nullable=False, comment='researcher / planner / executor / reviewer'),
    sa.Column('event_type', sa.String(length=64), nullable=False, comment='agent 自定义事件类型'),
    sa.Column('payload', sa.JSON(), nullable=False, comment='事件负载（≤64KB）'),
    sa.Column('parent_event_id', sa.BigInteger(), nullable=True, comment='父事件 ID（事件链，可选）'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_blackboard_owner_session', 'blackboard_events', ['owner_id', 'session_id'], unique=False)
    op.create_index('idx_blackboard_role_type', 'blackboard_events', ['agent_role', 'event_type'], unique=False)
    op.create_index('idx_blackboard_session_created', 'blackboard_events', ['session_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_blackboard_events_session_id'), 'blackboard_events', ['session_id'], unique=False)
    op.create_table('blackboard_sessions',
    sa.Column('owner_id', sa.BigInteger(), nullable=False, comment='session 所有者'),
    sa.Column('session_id', sa.String(length=64), nullable=False, comment='对外暴露的 session ID（UUID）'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='session 标题'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='open / closed'),
    sa.Column('closed_at', sa.String(length=32), nullable=True, comment='关闭时间（ISO8601 字符串，简单起见）'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blackboard_sessions_owner_id'), 'blackboard_sessions', ['owner_id'], unique=False)
    op.create_index(op.f('ix_blackboard_sessions_session_id'), 'blackboard_sessions', ['session_id'], unique=True)
    op.create_table('meeting_sessions',
    sa.Column('title', sa.String(length=200), nullable=False, comment='会议标题'),
    sa.Column('host_user_id', sa.BigInteger(), nullable=False, comment='主持人用户 ID'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='preparing / active / closed'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['host_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_sessions_host_user_id'), 'meeting_sessions', ['host_user_id'], unique=False)
    op.create_table('agent_executions',
    sa.Column('session_id', sa.BigInteger(), nullable=False, comment='关联的会议会话 ID'),
    sa.Column('agent_role', sa.String(length=32), nullable=False, comment='moderator / noter / decision / dispatcher'),
    sa.Column('trigger', sa.String(length=32), nullable=False, comment='speech_chunk / state_update'),
    sa.Column('input_snapshot', sa.JSON(), nullable=False, comment='触发时的输入快照（如语音文本 / 状态 diff）'),
    sa.Column('output', sa.String(length=65535), nullable=False, comment='Agent 输出内容（纯文本，最大 64KB）'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='thinking / done / failed'),
    sa.Column('finished_at', sa.DateTime(), nullable=True, comment='执行结束时间（thinking 阶段为 null）'),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['session_id'], ['meeting_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_execution_session_role', 'agent_executions', ['session_id', 'agent_role'], unique=False)
    op.create_index('idx_execution_status', 'agent_executions', ['status'], unique=False)
    op.create_index(op.f('ix_agent_executions_session_id'), 'agent_executions', ['session_id'], unique=False)
    op.create_table('meeting_blackboard',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False, comment='关联的会议会话 ID'),
    sa.Column('agent_role', sa.String(length=32), nullable=False, comment='moderator / noter / decision / dispatcher'),
    sa.Column('state_json', sa.JSON(), nullable=False, comment='该 Agent 写入的状态快照（≤64KB）'),
    sa.Column('version', sa.BigInteger(), nullable=False, comment='乐观锁版本号，每次更新 +1'),
    sa.Column('updated_at', sa.DateTime(), server_default='CURRENT_TIMESTAMP(6)', nullable=False, comment='最后更新时间'),
    sa.ForeignKeyConstraint(['session_id'], ['meeting_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_blackboard_session_role', 'meeting_blackboard', ['session_id', 'agent_role'], unique=True)
    op.create_index(op.f('ix_meeting_blackboard_session_id'), 'meeting_blackboard', ['session_id'], unique=False)
    op.drop_index(op.f('idx_sandbox_audit_biz'), table_name='sandbox_audit_log')
    op.drop_index(op.f('idx_sandbox_audit_risk'), table_name='sandbox_audit_log')
    op.drop_index(op.f('idx_sandbox_audit_user_created'), table_name='sandbox_audit_log')
    op.drop_table('sandbox_audit_log')
    op.alter_column('chat_conversations', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('chat_conversations', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('chat_messages', 'mode',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               server_default=None,
               existing_comment='回答模式',
               existing_nullable=False)
    op.alter_column('chat_messages', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('chat_messages', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('compliance_audit_logs', 'risk_category',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment='风险分类（money_laundering 等）',
               existing_comment='风险分类（money_laundering/insider_trading 等）',
               existing_nullable=True)
    op.alter_column('compliance_audit_logs', 'confidence',
               existing_type=mysql.FLOAT(),
               comment='Judge 置信度（0-1）',
               existing_comment='Judge 置信度 0-1',
               existing_nullable=True)
    op.alter_column('document_chunks', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('document_chunks', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('knowledge_documents', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               server_default=None,
               comment='解析状态',
               existing_comment='索引状态',
               existing_nullable=False)
    op.alter_column('knowledge_documents', 'parsed_char_count',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_comment='解析文本字符数',
               existing_nullable=False)
    op.alter_column('knowledge_documents', 'error_message',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000),
               comment='解析失败原因',
               existing_comment='索引失败原因',
               existing_nullable=True)
    op.alter_column('knowledge_documents', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('knowledge_documents', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('knowledge_documents', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('knowledge_documents', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('knowledge_documents', 'error_message',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000),
               comment='索引失败原因',
               existing_comment='解析失败原因',
               existing_nullable=True)
    op.alter_column('knowledge_documents', 'parsed_char_count',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               existing_comment='解析文本字符数',
               existing_nullable=False)
    op.alter_column('knowledge_documents', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               server_default=sa.text("'processing'"),
               comment='索引状态',
               existing_comment='解析状态',
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('knowledge_bases', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('document_chunks', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('document_chunks', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('compliance_audit_logs', 'confidence',
               existing_type=mysql.FLOAT(),
               comment='Judge 置信度 0-1',
               existing_comment='Judge 置信度（0-1）',
               existing_nullable=True)
    op.alter_column('compliance_audit_logs', 'risk_category',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               comment='风险分类（money_laundering/insider_trading 等）',
               existing_comment='风险分类（money_laundering 等）',
               existing_nullable=True)
    op.alter_column('chat_messages', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('chat_messages', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('chat_messages', 'mode',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               server_default=sa.text("'llm'"),
               existing_comment='回答模式',
               existing_nullable=False)
    op.alter_column('chat_conversations', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('chat_conversations', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.create_table('sandbox_audit_log',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False, comment='更新时间'),
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=False, comment='调用用户 ID'),
    sa.Column('biz_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32), nullable=False, comment='业务类型：chat/document/approval'),
    sa.Column('biz_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=False, comment='业务对象 ID'),
    sa.Column('text_hash', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=False, comment='原文 SHA-256 摘要（原文永不落库）'),
    sa.Column('risk_level', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16), nullable=False, comment='最终风险等级：low/medium/high'),
    sa.Column('matched_rules', mysql.JSON(), nullable=False, comment='命中规则详情（JSON）'),
    sa.Column('llm_reasoning', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=2048), nullable=True, comment='LLM 判定理由'),
    sa.Column('suggestions', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1024), nullable=True, comment='处置建议'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_sandbox_audit_user_created'), 'sandbox_audit_log', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_sandbox_audit_risk'), 'sandbox_audit_log', ['risk_level'], unique=False)
    op.create_index(op.f('idx_sandbox_audit_biz'), 'sandbox_audit_log', ['biz_type', 'biz_id'], unique=False)
    op.drop_index(op.f('ix_meeting_blackboard_session_id'), table_name='meeting_blackboard')
    op.drop_index('idx_blackboard_session_role', table_name='meeting_blackboard')
    op.drop_table('meeting_blackboard')
    op.drop_index(op.f('ix_agent_executions_session_id'), table_name='agent_executions')
    op.drop_index('idx_execution_status', table_name='agent_executions')
    op.drop_index('idx_execution_session_role', table_name='agent_executions')
    op.drop_table('agent_executions')
    op.drop_index(op.f('ix_meeting_sessions_host_user_id'), table_name='meeting_sessions')
    op.drop_table('meeting_sessions')
    op.drop_index(op.f('ix_blackboard_sessions_session_id'), table_name='blackboard_sessions')
    op.drop_index(op.f('ix_blackboard_sessions_owner_id'), table_name='blackboard_sessions')
    op.drop_table('blackboard_sessions')
    op.drop_index(op.f('ix_blackboard_events_session_id'), table_name='blackboard_events')
    op.drop_index('idx_blackboard_session_created', table_name='blackboard_events')
    op.drop_index('idx_blackboard_role_type', table_name='blackboard_events')
    op.drop_index('idx_blackboard_owner_session', table_name='blackboard_events')
    op.drop_table('blackboard_events')
    # ### end Alembic commands ###
